import type { Metadata } from "next";
import { mainFont } from "@/app/_styles/fonts";
import "./_styles/globals.css";
import Header from "@/app/_components/Header";
import Bottom from "@/app/_components/Bottom";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} antialiased `}>
        <Header />
        {children}
        <Bottom />
      </body>
    </html>
  );
}
